src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 * @ORM\Table(name="symfony_demo_post")
 *
 * Defines the properties of the Post entity to represent the blog posts.
 *
 * See https://symfony.com/doc/current/book/doctrine.html#creating-an-entity-class
 *
 * Tip: if you have an existing database, you can generate these entity class automatically.
 * See https://symfony.com/doc/current/cookbook/doctrine/reverse_engineering.html
 *
 * @author Ryan Weaver <weaverryan@gmail.com>
 * @author Javier Eguiluz <javier.eguiluz@gmail.com>
 * @author Yonel Ceruto <yonelceruto@gmail.com>
 */
class Post
{
    /**
     * Use constants to define configuration options that rarely change instead
     * of specifying them under parameters section in config/services.yaml file.
     *
     * See https://symfony.com/doc/current/best_practices/configuration.html#constants-vs-configuration-options
     */
    public const NUM_ITEMS = 10;

    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $slug;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="post.blank_summary")
     * @Assert\Length(max=255)
     */
    private $summary;

    /**
     * @var string
     *
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="post.blank_content")
     * @Assert\Length(min=10, minMessage="post.too_short_content")
     */
    private $content;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     */
    private $publishedAt;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=true)
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $author;

    /**
     * @var Comment[]|ArrayCollection
     *
     * @ORM\OneToMany(
     *      targetEntity="Comment",
     *      mappedBy="post",
     *      orphanRemoval=true,
     *      cascade={"persist"}
     * )
     * @ORM\OrderBy({"publishedAt": "DESC"})
     */
    private $comments;

    /**
     * @var Tag[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", cascade={"persist"})
     * @ORM\JoinTable(name="symfony_demo_post_tag")
     * @ORM\OrderBy({"name": "ASC"})
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category")
     * @ORM\JoinColumn(onDelete="SET NULL")
     * @ORM\JoinColumn(nullable=true)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $video_id;

    public function __construct()
    {
        $this->publishedAt = new \DateTime();
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): void
    {
        $this->slug = $slug;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): void
    {
        $this->content = $content;
    }

    public function getPublishedAt(): \DateTime
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTime $publishedAt): void
    {
        $this->publishedAt = $publishedAt;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(User $author): void
    {
        $this->author = $author;
    }

    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): void
    {
        $comment->setPost($this);
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
        }
    }

    public function removeComment(Comment $comment): void
    {
        $this->comments->removeElement($comment);
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): void
    {
        $this->summary = $summary;
    }

    public function addTag(Tag ...$tags): void
    {
        foreach ($tags as $tag) {
            if (!$this->tags->contains($tag)) {
                $this->tags->add($tag);
            }
        }
    }

    public function removeTag(Tag $tag): void
    {
        $this->tags->removeElement($tag);
    }

    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getImageName()
    {
        return $this->imageName;
    }

    public function setImageName($imageName)
    {
        $this->imageName = $imageName;
    }

    public function getVideoId(): ?string
    {
        return $this->video_id;
    }

    public function setVideoId(string $video_id): self
    {
        $this->video_id = $video_id;

        return $this;
    }
}

src/Controller/Admin/BlogController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Post;
use App\Form\PostType;
use App\Repository\PostRepository;
use App\Security\PostVoter;
use App\Service\FileUploader;
use App\Utils\Slugger;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Controller used to manage blog contents in the backend.
 *
 * Please note that the application backend is developed manually for learning
 * purposes. However, in your real Symfony application you should use any of the
 * existing bundles that let you generate ready-to-use backends without effort.
 *
 * See http://knpbundles.com/keyword/admin
 *
 * @Route("/admin/post")
 *
 * @author Ryan Weaver <weaverryan@gmail.com>
 * @author Javier Eguiluz <javier.eguiluz@gmail.com>
 */
class BlogController extends AbstractController
{
    /**
     * Lists all Post entities.
     *
     * This controller responds to two different routes with the same URL:
     *   * 'admin_post_index' is the route with a name that follows the same
     *     structure as the rest of the controllers of this class.
     *   * 'admin_index' is a nice shortcut to the backend homepage. This allows
     *     to create simpler links in the templates. Moreover, in the future we
     *     could move this annotation to any other controller while maintaining
     *     the route name and therefore, without breaking any existing link.
     *
     * @Route("/", methods={"GET"}, name="admin_index")
     * @Route("/", methods={"GET"}, name="admin_post_index")
     *
     * @param PostRepository $posts
     * @return Response
     *
     */
    public function index(PostRepository $posts): Response
    {
        $authorPosts = $posts->findBy([], ['publishedAt' => 'DESC']);

        return $this->render('admin/blog/index.html.twig', ['posts' => $authorPosts]);
    }

    /**
     * Creates a new Post entity.
     *
     * @Route("/new", methods={"GET", "POST"}, name="admin_post_new")
     *
     * NOTE: the Method annotation is optional, but it's a recommended practice
     * to constraint the HTTP methods each controller responds to (by default
     * it responds to all methods).
     *
     * @param Request $request
     * @param FileUploader $fileUploader
     * @return Response
     * @throws \Exception
     */
    public function new(Request $request, FileUploader $fileUploader): Response
    {
        $post = new Post();
        $post->setAuthor($this->getUser());

        // See https://symfony.com/doc/current/book/forms.html#submitting-forms-with-multiple-buttons
        $form = $this->createForm(PostType::class, $post)
            ->add('saveAndCreateNew', SubmitType::class);

        $form->handleRequest($request);

        // the isSubmitted() method is completely optional because the other
        // isValid() method already checks whether the form is submitted.
        // However, we explicitly add it to improve code readability.
        // See https://symfony.com/doc/current/best_practices/forms.html#handling-form-submits
        if ($form->isSubmitted() && $form->isValid()) {
            $post->setSlug(Slugger::slugify($post->getTitle()));

            /** @var UploadedFile $image */
            $image = $form['image']->getData();

            if($image){
                $newFilename = $fileUploader->upload($image);
                $post->setImageName($newFilename);
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($post);
            $em->flush();

            // Flash messages are used to notify the user about the result of the
            // actions. They are deleted automatically from the session as soon
            // as they are accessed.
            // See https://symfony.com/doc/current/book/controller.html#flash-messages
            $this->addFlash('success', 'post.created_successfully');

            if ($form->get('saveAndCreateNew')->isClicked()) {
                return $this->redirectToRoute('admin_post_new');
            }

            return $this->redirectToRoute('admin_post_index');
        }

        return $this->render('admin/blog/new.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Finds and displays a Post entity.
     *
     * @Route("/{id<\d+>}", methods={"GET"}, name="admin_post_show")
     *
     * @param Post $post
     * @return Response
     */
    public function show(Post $post): Response
    {
        // This security check can also be performed
        // using an annotation: @IsGranted("show", subject="post", message="Posts can only be shown to their authors.")

        return $this->render('admin/blog/show.html.twig', [
            'post' => $post,
        ]);
    }

    /**
     * Displays a form to edit an existing Post entity.
     *
     * @Route("/{id<\d+>}/edit",methods={"GET", "POST"}, name="admin_post_edit")
     *
     * @param Request $request
     * @param Post $post
     * @param FileUploader $fileUploader
     * @return Response
     * @throws \Exception
     */
    public function edit(Request $request, Post $post, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $post->setSlug(Slugger::slugify($post->getTitle()));

            /** @var UploadedFile $image */
            $image = $form['image']->getData();

            if($image){
                //upload image
                $newFilename = $fileUploader->upload($image);
                // delete old image
                if(null !== $post->getImageName()){
                    $fileUploader->delete($post->getImageName());
                }
                $post->setImageName($newFilename);
            }

            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'post.updated_successfully');

            return $this->redirectToRoute('admin_post_edit', ['id' => $post->getId()]);
        }

        return $this->render('admin/blog/edit.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Deletes a Post entity.
     *
     * @Route("/{id}/delete", methods={"POST"}, name="admin_post_delete")
     *
     * @param Request $request
     * @param Post $post
     * @param FileUploader $fileUploader
     * @return Response
     */
    public function delete(Request $request, Post $post, FileUploader $fileUploader): Response
    {
        if (!$this->isCsrfTokenValid('delete', $request->request->get('token'))) {
            return $this->redirectToRoute('admin_post_index');
        }

        // Delete the tags associated with this blog post. This is done automatically
        // by Doctrine, except for SQLite (the database used in this application)
        // because foreign key support is not enabled by default in SQLite
        $post->getTags()->clear();

        // delete image
        if(null !== $post->getImageName()){
            $fileUploader->delete($post->getImageName());
        }

        $em = $this->getDoctrine()->getManager();
        $em->remove($post);
        $em->flush();

        $this->addFlash('success', 'post.deleted_successfully');

        return $this->redirectToRoute('admin_post_index');
    }
}

templates/blog/_category_block.html.twig
<div class="section list-categories-bloc">
    <div class="well well-lg">

        {% if categories is defined %}

            <h4>Категории :</h4>

            <ul class="cat-menu">

                {% for item in categories %}

                    {% set category = item['category'] %}
                    {% set count = item['count'] %}

                    {% set selectedCategory = '' %}
                    {% if category.id == categoryIdSelected %}
                        {% set selectedCategory = 'class=category-selected' %}
                    {% endif %}

                    <li>
                        <a {{ selectedCategory }} href="{{ path('homepage',{'get[category]': category.id}) }}" title="{{ category.name }}">{{ category.name }} ({{ count }})</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</div>

templates/blog/_comment_form.html.twig
{#
    By default, forms enable client-side validation. This means that you can't
    test the server-side validation errors from the browser. To temporarily
    disable this validation, add the 'novalidate' attribute:

    {{ form_start(form, {method: ..., action: ..., attr: {novalidate: 'novalidate'}}) }}
#}

{{ form_start(form, {method: 'POST', action: path('comment_new', {'postSlug': post.slug})}) }}
    {#  instead of displaying form fields one by one, you can also display them
        all with their default options and styles just by calling to this function:

        {{ form_widget(form) }}
    #}

    <fieldset>
        <legend>
            <i class="fa fa-comment" aria-hidden="true"></i> {{ 'title.add_comment'|trans }}
        </legend>

        {# Render any global form error (e.g. when a constraint on a public getter method failed) #}
        {{ form_errors(form) }}

        <div class="form-group {% if not form.content.vars.valid %}has-error{% endif %}">
            {{ form_row(form.name) }}
            {{ form_label(form.content, 'label.content') }}

            {# Render any errors for the "content" field (e.g. when a class property constraint failed) #}
            {{ form_errors(form.content) }}

            {{ form_widget(form.content, {attr: {rows: 10}}) }}

            {{ form_help(form.content) }}
        </div>
        <div class="g-recaptcha" data-sitekey="6LdB3sQUAAAAABXxx9XXr6QNUCNoJTA3ju71Gf1m"></div>

        <div class="form-group">
            <button class="btn btn-primary pull-right" type="submit">
                <i class="fa fa-paper-plane" aria-hidden="true"></i> {{ 'action.publish_comment'|trans }}
            </button>
        </div>
    </fieldset>
{{ form_end(form) }}

templates/blog/_delete_post_confirmation.html.twig
{# Bootstrap modal, see http://getbootstrap.com/javascript/#modals #}
<div class="modal fade" id="confirmationModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <h4>{{ 'delete_post_modal.title'|trans }}</h4>
                <p>{{ 'delete_post_modal.body'|trans }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="btnNo" data-dismiss="modal">
                    <i class="fa fa-ban" aria-hidden="true"></i> {{ 'label.cancel'|trans }}
                </button>
                <button type="button" class="btn btn-danger" id="btnYes" data-dismiss="modal">
                    <i class="fa fa-trash" aria-hidden="true"></i> {{ 'label.delete_post'|trans }}
                </button>
            </div>
        </div>
    </div>
</div>

templates/blog/_post_tags.html.twig
{% if not post.tags.empty %}

    {% if titleBloc is defined %}
        <h4 class="align-content-center">{{ 'label.tags' | trans }} : </h4>
    {% endif %}

    <p class="post-tags">

        {% set selectedCategory = app.request.query.get('tag') %}
        {% if selectedTag is defined and selectedTag is not null %}
            {% set selectedCategory = selectedTag %}
        {% endif %}

        {% for tag in post.tags %}
            <a href="{{ path('blog_index', {'tag': tag.name == app.request.query.get('tag') ? null : tag.name}) }}"
               class="label label-{{ tag.name == selectedCategory ? 'success' : 'default' }}"
            >
                <i class="fa fa-tag"></i> {{ tag.name }}
            </a>
        {% endfor %}
    </p>
{% endif %}

templates/blog/_relevant_post.html.twig
{% if posts is not empty %}
    <div id="post-relevant" class="well">
        <h4>{{'label.relevant_post'|trans}} :</h4>
        <div class="row">
            {% for post in posts  %}
                <div class="col-sm-3">
                    {% set thumbnail = 'https://i.ytimg.com/vi/'~ post.videoId ~'/maxresdefault.jpg' %}
                    {% if post.imageName and post.videoId is null %}
                        {% set thumbnail = asset('/uploads/images/' ~ post.imageName) | imagine_filter('post_show') %}
                    {% endif %}
                    <a href="{{ path('blog_post', {slug: post.slug}) }}">
                        <img class="responsive" src="{{thumbnail}}" title="{{ post.title }}" alt="{{ post.title }}" />
                    </a>
                </div>
                <div class="col-sm-9">
                    <a href="{{ path('blog_post', {slug: post.slug}) }}" title="{{ post.title }}">
                        {{ post.title }}
                    </a>
                    <p>{{ post.summary }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endif %}

templates/blog/_rss.html.twig
<div class="section rss">
    <a href="{{ path('blog_rss', app.request.query.all) }}">
        <i class="fa fa-rss" aria-hidden="true"></i> {{ 'menu.rss'|trans }}
    </a>
</div>

templates/blog/_socials_buttons.html.twig
<div class="well well-lg">
    <a href="https://www.facebook.com/bonjourfrancia/" type="button" role="button" title="Facebook"><i class="socials fa fa-facebook"></i></a>
    <a href="https://www.youtube.com/channel/UCTH7m7287DvLVbt4FmbUwyA?sub_confirmation=1" type="button" role="button" title="Youtube"><i class="socials fa fa-youtube"></i></a>
    <a href="https://vk.com/france_bonjour" type="button" role="button" title="VK"><i class="socials fa fa-vk"></i></a>
    <a href="https://twitter.com/dennedblog" type="button" role="button" title="Twitter"><i class="socials fa fa-twitter"></i></a>
</div>

templates/blog/about.html.twig
<div class="section about">
    <div class="well well-lg">
        <p>
            {{ 'help.app_description'|trans|raw }}
        </p>
        <p>
            {{ 'help.more_information'|trans|raw }}
        </p>
    </div>
</div>

{# it's not mandatory to set the timezone in localizeddate(). This is done to
   avoid errors when the 'intl' PHP extension is not available and the application
   is forced to use the limited "intl polyfill", which only supports UTC and GMT #}
<!-- Fragment rendered on {{ 'now'|localizeddate('long', 'long', null, 'UTC') }} -->

templates/blog/comment_form_error.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'comment_form_error' %}

{% block stylesheets %}
    {{ parent() }}
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock %}

{% block main %}
    <h1 class="text-danger">{{ 'title.comment_error'|trans }}</h1>

    <div class="well">
        {{ include('blog/_comment_form.html.twig') }}
    </div>
{% endblock %}

{% block sidebar %}
    {{ render(controller('App\\Controller\\CategoryController::showCategories')) }}
    {{ render(controller('App\\Controller\\TagController::showTagsCloud')) }}
    {{ include('blog/_socials_buttons.html.twig') }}
    {{ include('blog/_rss.html.twig') }}
{% endblock %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'blog_index' %}

{% block main %}
    {% for post in paginator.results %}
        <article class="post">
            <h2>
                <a href="{{ path('blog_post', {slug: post.slug}) }}" title="{{ post.title }}">
                    {{ post.title }}
                </a>
            </h2>

            <p class="post-metadata">
                <span class="metadata"><i class="fa fa-calendar"></i> {{ post.publishedAt|date('d/m/Y h:m') }}</span>
            </p>

            <div class="form-group size-image">
                {% if post.imageName and post.videoId is null %}
                    <img class="responsive" src="{{asset('/uploads/images/' ~ post.imageName) | imagine_filter('post_show')}}" title="{{ post.title }}" alt="{{ post.title }}" />
                {% else %}
                    {% set thumbnail = 'https://i.ytimg.com/vi/'~ post.videoId ~'/maxresdefault.jpg' %}
                    <img class="responsive" src="{{thumbnail}}" title="{{ post.title }}" alt="{{ post.title }}" />
                {% endif %}
            </div>

            <p>{{ post.summary }}</p>

            {{ include('blog/_post_tags.html.twig') }}
        </article>
    {% else %}
        <div class="well">{{ 'post.no_posts_found'|trans }}</div>
    {% endfor %}

    {% if paginator.hasToPaginate %}
        <div class="navigation text-center">
            <ul class="pagination">
                {% if paginator.hasPreviousPage %}
                    <li class="prev"><a href="{{ path('blog_index_paginated', {page: paginator.previousPage}) }}" rel="previous"><i class="fa fw fa-long-arrow-left"></i> Previous</a></li>
                {% else %}
                    <li class="prev disabled"><span><i class="fa fw fa-arrow-left"></i> Previous</span></li>
                {% endif %}

                {% for i in 1..paginator.lastPage %}
                    {% if i == paginator.currentPage %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="{{ path('blog_index_paginated', {page: i}) }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if paginator.hasNextPage %}
                    <li class="next"><a href="{{ path('blog_index_paginated', {page: paginator.nextPage}) }}" rel="next">Next <i class="fa fw fa-arrow-right"></i></a></li>
                {% else %}
                    <li class="next disabled"><span>Next <i class="fa fw fa-arrow-right"></i></span></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

{% block sidebar %}
    {{ render(controller('App\\Controller\\CategoryController::showCategories')) }}
    {{ render(controller('App\\Controller\\TagController::showTagsCloud')) }}
    {{ include('blog/_socials_buttons.html.twig') }}
    {{ include('blog/_rss.html.twig') }}
{% endblock %}

templates/blog/index.xml.twig
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
    <channel>
        <title>{{ 'rss.title'|trans }}</title>
        <description>{{ 'rss.description'|trans }}</description>
        <pubDate>{{ 'now'|date('r', timezone='GMT') }}</pubDate>
        <lastBuildDate>{{ (paginator.results|last).publishedAt|default('now')|date('r', timezone='GMT') }}</lastBuildDate>
        <link>{{ url('blog_index') }}</link>
        <language>{{ app.request.locale }}</language>

        {% for post in paginator.results %}
            <item>
                <title>{{ post.title }}</title>
                <description>{{ post.summary }}</description>
                <link>{{ url('blog_post', {'slug': post.slug}) }}</link>
                <guid>{{ url('blog_post', {'slug': post.slug}) }}</guid>
                <pubDate>{{ post.publishedAt|date(format='r', timezone='GMT') }}</pubDate>
                <author>{{ post.author.email ?? ''}}</author>
                {% for tag in post.tags %}
                    <category>{{ tag.name }}</category>
                {% endfor %}
            </item>
        {% endfor %}
    </channel>
</rss>

templates/blog/post_show.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'blog_post_show' %}

{% block meta %}
    <meta name="title" content="{{ post.title }}">
    <meta name="description" content="{{ post.title }} DENNEDBLOG - Расскажу как я переехал во Францию, где учился и как нашел работу."/>
    <meta name="keywords" content="{{ post.tags|join(',') }}"/>
    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{app.request.uri}}">
    <meta property="og:title" content="{{ post.title }}">
    <meta property="og:description" content="{{ post.title }} DENNEDBLOG - Расскажу как я переехал во Францию, где учился и как нашел работу.">

    {% set image = 'https://i.ytimg.com/vi/'~ post.videoId ~'/maxresdefault.jpg' %}
    {% if post.imageName and post.videoId is null %}
        {% set image = asset('/uploads/images/' ~ post.imageName) | imagine_filter('post_show') %}
    {% endif %}
    <meta property="og:image" content="{{ image }}">
{% endblock %}

{% block title %}{{ 'site'|trans }} - {{ post.title }} {% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock %}

{% block main %}
    <h1>{{ post.title }}</h1>

    <p class="post-metadata">
        <span class="metadata"><i class="fa fa-calendar"></i> {{ post.publishedAt|date('d/m/Y h:m') }}</span>
    </p>

    <div class="form-group size-image">
        {% if post.imageName and post.videoId is null %}
            <img class="responsive" src="{{asset('/uploads/images/' ~ post.imageName) | imagine_filter('post_show')}}" title="{{ post.title }}" alt="{{ post.title }}" />
        {% else %}
            {% set thumbnail = 'https://i.ytimg.com/vi/'~ post.videoId ~'/maxresdefault.jpg' %}
            <img class="responsive" src="{{thumbnail}}" title="{{ post.title }}" alt="{{ post.title }}" />
        {% endif %}
    </div>

    {{ post.content|md2html }}

    {% if post.videoId is not null %}
        {% set linkVideo = 'https://www.youtube.com/embed/'~post.videoId %}

        <iframe width="100%" height="400" src={{ linkVideo }} frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    {% endif %}

    {{ include('blog/_post_tags.html.twig') }}

    {{ render(controller('App\\Controller\\BlogController::getRelevantPosts', {'tags': post.tags, 'id': post.id, 'limit' : 3})) }}

    <div id="post-add-comment" class="well">
        {{ render(controller('App\\Controller\\BlogController::commentForm', {'id': post.id})) }}
    </div>

    <h3>
        <i class="fa fa-comments" aria-hidden="true"></i> {{ 'post.num_comments'|trans({ 'count': post.comments|length }) }}
    </h3>

    {% for comment in post.comments %}
        <div class="row post-comment">
            <a name="comment_{{ comment.id }}"></a>
            <h4 class="col-sm-3">
                <strong>{{ comment.name }}</strong> {{ 'post.commented_on'|trans }}
                <strong>{{ comment.publishedAt|date('d/m/Y h:m') }}</strong>
            </h4>
            <div class="col-sm-9">
                {{ comment.content|md2html }}
            </div>
        </div>
    {% else %}
        <div class="post-comment">
            <p>{{ 'post.no_comments'|trans }}</p>
        </div>
    {% endfor %}
{% endblock %}

{% block sidebar %}
    {{ render(controller('App\\Controller\\CategoryController::showCategories')) }}
    {{ render(controller('App\\Controller\\TagController::showTagsCloud')) }}
    {{ include('blog/_socials_buttons.html.twig') }}
    {{ include('blog/_rss.html.twig') }}
{% endblock %}